version: '3'
services:
    backup:
        build:
            context: https://github.com/entu/backup.git
        container_name: backup
        restart: on-failure
        environment:
            MYSQL_HOST:
            MYSQL_PORT:
            MYSQL_USER:
            MYSQL_PASSWORD:
            S3_BUCKET:
            S3_KEY:
            S3_SECRET:
        volumes:
            - /data/backup:/usr/src/entu-backup/dump
            - /data/rds-combined-ca-bundle.pem:/usr/src/entu-backup/ssl/rds-combined-ca-bundle.pem:ro
